### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by mattias-fjellstrom** [mattias-fjellstrom-org/mattias-fjellstrom-org#1]
Remember to set up the rest of the repository yourself!

## Tasks

- [ ] Add a good README.md
- [ ] Add a LICENSE file
- [ ] Add a CONTRIBUTING.md
- [ ] Add a CODE_OF_CONDUCT.md
- [ ] Add a SECURITY.md
- [ ] Add a SUPPORT.md
- [ ] Add a CHANGELOG.md
- [ ] Add a .github/PULL_REQUEST_TEMPLATE.md
- [ ] Add a .github/ISSUE_TEMPLATE.md
- [ ] Add a .github/CODEOWNERS

Good luck!
